apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frodo.fullname" . }}
  labels:
    {{- include "frodo.labels" . | nindent 4 }}
data:
  QUARKUS_DATASOURCE_JDBC_URL: {{ .Values.firebird.jdbcUrl | quote }}
  QUARKUS_DATASOURCE_USERNAME: {{ .Values.firebird.user | quote }}
