# Gradle properties

quarkusPluginId=io.quarkus
quarkusPluginVersion=3.34.1
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.34.1
action.custom-1=Debug
action.custom-1.args=--configure-on-demand -w -x check quarkusDev
action.debug.args=--configure-on-demand -w -x check quarkusDev
