# Gradle properties

# Project version
projectVersion=1.4.0

# Quarkus
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.34.1
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.34.1
action.debug.args=--configure-on-demand -w -x check quarkusDev
