# Gradle properties

# Project version
projectVersion=2.1.0-SNAPSHOT

# Quarkus
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.35.3
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.35.3
action.custom-1=storybook
action.custom-1.args=storybook
action.debug.args=--configure-on-demand -w -x check quarkusDev
netbeans.org-netbeans-modules-javascript2-requirejs.enabled=true
netbeans.org-netbeans-modules-javascript2-json.json_2e_comments=true
